// Generated by CoffeeScript 1.6.3
(function() {
  var $current, done, effect;

  effect = kendo.fx;

  $current = null;

  done = function() {
    $current = null;
    return $.publish("/effects/done");
  };

  $.subscribe("/effects/setup", function(e, el) {
    return el.find("[data-effect]").each(function() {
      var $that;
      $that = $(this);
      effect = $that.data("effect");
      switch (effect) {
        case "replace":
          return $that.find("> *:not(:first-child)").hide();
        case "fragment":
          return $that.children().hide();
        case "fadeIn":
          return $that.hide();
      }
    });
  });

  $.subscribe("/effects/process", function(e, el) {
    var $el, $next;
    $el = $(el);
    if ($current === null) {
      $current = $el.children().first();
    }
    switch ($el.data("effect")) {
      case "replace":
        $next = $current.next();
        return kendo.fx($el).expand("vertical").duration(1000).reverse().then(function() {
          $current.hide();
          $next.show();
          $current = $next;
          if ($current.next().length === 0) {
            done();
          }
          return setTimeout(function() {
            return kendo.fx($el).expand("vertical").duration(1000).play().then(function() {});
          }, 1);
        });
      case "fragment":
        return kendo.fx($current).fade("in").play().then(function() {
          if ($current.next().length === 0) {
            return done();
          } else {
            return $current = $current.next();
          }
        });
      case "fadeIn":
        return kendo.fx($el).fade("in").play().then(function() {
          return done();
        });
    }
  });

}).call(this);
