// Generated by CoffeeScript 1.6.3
(function() {
  var router;

  router = new kendo.Router();

  $.subscribe("/router/navigate", function(e, path) {
    return router.navigate(path);
  });

  $.subscribe("/router/start", function() {
    return router.start();
  });

  router.route("/slides/:id", function(id) {
    return $.publish("/slides/show", [parseInt(id, 0)]);
  });

  router.route("/", function() {
    return router.navigate("/slides/1");
  });

}).call(this);
