// Generated by CoffeeScript 1.6.3
(function() {
  var bootstrap, paused, viewModel;

  paused = function(flag) {
    return $.publish("/controls/paused", [flag]);
  };

  bootstrap = true;

  viewModel = kendo.observable({
    toggleBootstrap: function() {
      var $bootstrap;
      $bootstrap = $("#bootstrap");
      if (bootstrap) {
        $bootstrap.attr("rel", "notastylesheet");
        return bootstrap = false;
      } else {
        $bootstrap.attr("rel", "stylesheet");
        return bootstrap = true;
      }
    },
    pauseControls: function() {
      return paused(true);
    },
    unpauseControls: function() {
      paused(false);
      return this.set("editorVisible", false);
    },
    updateSampleQuery: function(e) {
      var style;
      style = $("#scoped-sample-query");
      style.html($(e.currentTarget).text());
      return paused(false);
    },
    screenSize: $(window).width(),
    updateHtml: function(e) {
      return setTimeout(function() {
        var $slide, $source, $target;
        $source = $(e.currentTarget);
        $slide = $source.closest(".slide");
        $target = $slide.find($source.data("target"));
        if ($target.length > 0) {
          return $slide.find($target).html($source.text());
        } else {
          return $source.next().html($source.text());
        }
      }, 100);
    },
    containerWidth: 0,
    containerPadding: 0,
    containerMargin: 0,
    editorVisible: false,
    showEditor: function() {
      var visible;
      visible = this.get("editorVisible");
      if (visible) {
        return this.set("editorVisible", false);
      } else {
        return this.set("editorVisible", true);
      }
    }
  });

  $(window).resize(function() {
    viewModel.set("screenSize", $(this).width());
    return viewModel.set("containerWidth", $(".container-demo").width());
  });

  window.APP.slides.viewModel = viewModel;

}).call(this);
